### ISSUE TITLE
it.dgc.verificac19.data.local.BlackListDao' that could not be found.

### ISSUE THREAD

**Issue by lorenzo-lambertini** [hrnext/it-dgc-verificac19-spring#1]
provando ad importare la libreria all'interno di un nostro progetto non mi trova il BlackListDao.

Ho già aggiunto :
`@SpringBootApplication(scanBasePackages = { "mypackage", "it.dgc.verificac19" })`

e cosi facendo riesco a vedere tutti gli altri bean, ma non riesce a fare DI su BlackListDao nella classe VerifierRepositoryImpl.

**Comment by marcoserafini2** [comment]
Aggiungi queste due annotations all'interno del tuo progetto.

Per lo scan delle `@Entity`
`@EntityScan(basePackages = "it.dgc.verificac19")
`

Per lo scan dei `@Repository` JPA di Spring Data
`@EnableJpaRepositories("it.dgc.verificac19")
`

**Comment by lorenzo-lambertini** [comment]
grazie, cosi funziona.
