### ISSUE TITLE
errore exemption pass

### ISSUE THREAD

**Issue by lorenzo-lambertini** [hrnext/it-dgc-verificac19-spring#13]
Ciao,
sto provando a parsare un greenpass da esenzione, primo errore che ho già sistemato è che nella classe it.dgc.verificac19.model.VerificaC19DigitalCovidCertificate viene usato jackson e nel modello(it.dgc.verificac19.model.Exemption) non sono mappate con jackson ma con gson le properties e quindi non le riconosce(cosi per intenderci) : 

```
  @JsonProperty("tg")
// @SerializedName("tg")
  private String disease;

//  @SerializedName("co")
  @JsonProperty("co")
  private String countryOfVaccination;

//  @SerializedName("is")
  @JsonProperty("is")
  private String certificateIssuer;

//  @SerializedName("ci")
  @JsonProperty("ci")
  private String certificateIdentifier;

//  @SerializedName("df")
  @JsonProperty("df")
  private String certificateValidFrom;

//  @SerializedName("du")
  @JsonProperty("du")
  private String certificateValidUntil; 

```

ma incorro in un altro problema : 

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "cu" (class it.dgc.verificac19.model.Exemption), not marked as ignorable (6 known properties: "du", "df", "tg", "ci", "is", "co"])

sembra che manchi una property o una sia configurata male, sapreste aiutarmi?

**Comment by francesconigro** [comment]
Ciao @lorenzo-lambertini , essendo i CRT E fuori schema DGC, non ho potuto fare un test puntuale. Mi sapresti fornire il tuo CRT di esempio per debuggare? Grazie

**Comment by lorenzo-lambertini** [comment]
Ciao @francesconigro , ti ho girato il certificato alla tua mail presente sul repo.

**Comment by francesconigro** [comment]
Grazie

**Comment by francesconigro** [comment]
Ciao @lorenzo-lambertini ora dovrebbe essere tutto ok. Grazie per la segnalazione e per il supporto nel fornirmi un CRT reale.
