### ISSUE TITLE
Problema import

### ISSUE THREAD

**Issue by luca-mc** [hrnext/it-dgc-verificac19-spring#6]
Sto importando con maven il jar del progetto it-dgc-verificac19-spring-core ma sto avendo dei problemi, per ora si avvia spring boot ma quasi alla fine mi da questo errore:

`[org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (ServerService Thread Pool -- 85) Table 'myproject.blacklist' doesn't exist`

Ho guardato nel progetto e viene utilizzata una tabella blacklist, devo configurare il progetto in modo che si connetta ad un db remoto dove trovero' questa tabella o devo definirla nel mio db o il problema e' un altro?

Anche l'altro problema riguarda l'import ed e' il seguente:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    deployment.myproject-0.6.8.war//it.dgc.verificac19.data.VerifierRepositoryImpl.fetchValidationRules(VerifierRepositoryImpl.java:234)

The following method did not exist:

    'java.util.List it.dgc.verificac19.data.local.BlackListDao.saveAllAndFlush(java.lang.Iterable)'

The method's class, it.dgc.verificac19.data.local.BlackListDao, is available from the following locations:

    vfs:/D:/webservers/wildfly-21.0.2.Final/standalone/deployments/myproject.war/WEB-INF/lib/it-dgc-verificac19-spring-core-0.0.2.jar/it/dgc/verificac19/data/local/BlackListDao.class

The class hierarchy was loaded from the following locations:

    it.dgc.verificac19.data.local.BlackListDao: vfs:/D:/webservers/wildfly-21.0.2.Final/standalone/deployments/myproject.war/WEB-INF/lib/it-dgc-verificac19-spring-core-0.0.2.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of it.dgc.verificac19.data.local.BlackListDao
```

Come suggerito dal messaggio ho controllato gli import nel pom.xml ma di import del jar(it-dgc-verificac19-spring-core) ne ho effettuato solo uno, per quanto riguarda BlackListDao non ho importato niente dal momento che e' contenuto nel jar di it-dgc-verificac19-spring-core.

**Comment by marcoserafini2** [comment]
Ciao @luca-mc, qual è la tua attuale configurazione?
Vedo dai log che stai provando a deployare un WAR su Wildfly 21 (non ho avuto modo di testare questa configurazione)
Al di là di questo, ti rispondo alla prima domanda: Devi configurare il progetto in modo che si connetta ad un DB nel quale devono essere presenti tutte le tabelle richieste dall'SDK
Come hai configurato la connessione JDBC, che DB stai utilizzando?

Aggiungi queste due proprietà se hai la necessità di creare/aggiornare le tabelle in fase di startup
```
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
```

**Comment by luca-mc** [comment]
Come webserver utilizzo Wildfly 21
Il DB che sto utilizzando e' MySQL e per effettuare la connessione e per le operazioni CRUD utilizzo JPA.

**Comment by marcoserafini2** [comment]
> Come webserver utilizzo Wildfly 21 Il DB che sto utilizzando e' MySQL e per effettuare la connessione e per le operazioni CRUD utilizzo JPA.

Vuoi condividermi il file di properties utilizzato?

**Comment by luca-mc** [comment]
application.properties:

```
spring.datasource.jndi-name=java:jboss/datasources/myprojectDS
```

standalone.xml:

```
<datasource jndi-name="java:jboss/datasources/myprojectDS" pool-name="myprojectDS" statistics-enabled="true">
	<connection-url>jdbc:mysql://test.myproject.it:3306/myproject</connection-url>
	<driver-class>com.mysql.cj.jdbc.Driver</driver-class>
	<driver>mysql</driver>
	<pool>
		<min-pool-size>100</min-pool-size>
		<max-pool-size>10000</max-pool-size>
		<prefill>true</prefill>
	</pool>
	<security>
		<user-name>user</user-name>
		<password>pass</password>
	</security>
	<validation>
		<valid-connection-checker class-name="org.jboss.jca.adapters.jdbc.extensions.mysql.MySQLValidConnectionChecker"/>
		<background-validation>true</background-validation>
		<exception-sorter class-name="org.jboss.jca.adapters.jdbc.extensions.mysql.MySQLExceptionSorter"/>
	</validation>
</datasource>
```

**Comment by luca-mc** [comment]
Per quanto riguarda l'import della libreria ho risolto con la tua soluzione.

Grazie mille per l'assistenza
